/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as HostCitiesRouteImport } from './routes/host-cities'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as ApiPublicHooksSyncFifaRouteImport } from './routes/api/public/hooks/sync-fifa'

const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const HostCitiesRoute = HostCitiesRouteImport.update({
  id: '/host-cities',
  path: '/host-cities',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => MatchesRoute,
} as any)
const ApiPublicHooksSyncFifaRoute = ApiPublicHooksSyncFifaRouteImport.update({
  id: '/api/public/hooks/sync-fifa',
  path: '/api/public/hooks/sync-fifa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/host-cities': typeof HostCitiesRoute
  '/matches': typeof MatchesRouteWithChildren
  '/news': typeof NewsRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/api/public/hooks/sync-fifa': typeof ApiPublicHooksSyncFifaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/host-cities': typeof HostCitiesRoute
  '/matches': typeof MatchesRouteWithChildren
  '/news': typeof NewsRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/api/public/hooks/sync-fifa': typeof ApiPublicHooksSyncFifaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/host-cities': typeof HostCitiesRoute
  '/matches': typeof MatchesRouteWithChildren
  '/news': typeof NewsRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/api/public/hooks/sync-fifa': typeof ApiPublicHooksSyncFifaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/host-cities'
    | '/matches'
    | '/news'
    | '/matches/$matchId'
    | '/api/public/hooks/sync-fifa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/host-cities'
    | '/matches'
    | '/news'
    | '/matches/$matchId'
    | '/api/public/hooks/sync-fifa'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/host-cities'
    | '/matches'
    | '/news'
    | '/matches/$matchId'
    | '/api/public/hooks/sync-fifa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  HostCitiesRoute: typeof HostCitiesRoute
  MatchesRoute: typeof MatchesRouteWithChildren
  NewsRoute: typeof NewsRoute
  ApiPublicHooksSyncFifaRoute: typeof ApiPublicHooksSyncFifaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-cities': {
      id: '/host-cities'
      path: '/host-cities'
      fullPath: '/host-cities'
      preLoaderRoute: typeof HostCitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/api/public/hooks/sync-fifa': {
      id: '/api/public/hooks/sync-fifa'
      path: '/api/public/hooks/sync-fifa'
      fullPath: '/api/public/hooks/sync-fifa'
      preLoaderRoute: typeof ApiPublicHooksSyncFifaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MatchesRouteChildren {
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesMatchIdRoute: MatchesMatchIdRoute,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  HostCitiesRoute: HostCitiesRoute,
  MatchesRoute: MatchesRouteWithChildren,
  NewsRoute: NewsRoute,
  ApiPublicHooksSyncFifaRoute: ApiPublicHooksSyncFifaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
